include: package:very_good_analysis/analysis_options.5.1.0.yaml
linter:
  rules:
    directives_ordering: false
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    sort_pub_dependencies: false
analyzer:
  errors:
    invalid_annotation_target: ignore
    todo: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
