name: jakislife
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  app_links: ^3.5.1
  audioplayers: ^5.2.1
  auto_route: ^7.8.4
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.7
  cloud_functions: ^4.6.7
  equatable: ^2.0.5
  firebase_analytics: ^10.8.9
  firebase_auth: ^4.17.7
  firebase_core: ^2.25.5
  firebase_messaging: ^14.7.18
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_google_wallet: ^0.1.4
  flutter_local_notifications: ^16.3.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  rive: ^0.13.4
  uuid: ^4.3.3

dev_dependencies:
  auto_route_generator: ^7.3.2
  bloc_test: ^9.1.4
  build_runner: ^2.4.8
  flutter_gen_runner: ^5.4.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    rive: true

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/rive/
    - assets/sounds/
    - assets/svg/
    - packages/flutter_google_wallet/assets/svg/button/frFR_add_to_google_wallet_wallet-button.svg
    - packages/flutter_google_wallet/assets/svg/button/enUS_add_to_google_wallet_wallet-button.svg
  
